// React/frontend/src/components/Dog/Dog.tsx
import {useState} from "react";
import hund from "../../assets/dog.png"
import katt from "../../assets/katt.png"
import "./Dog.css"
import Button from "../Button/Button";

const Dog = () => {

    const [showDog, setShowDog] = useState<boolean>(false)

    return (
        <div className="dog-container">
            <img
            className='dog-image'
            alt="dog"
            src={showDog ? hund : katt}
            />
            <Button showDog={showDog} setShowDog={setShowDog}/>
        </div>
    )

}
export default Dog;

// Angular/src/app/components/dog/dog.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dog',
  templateUrl: './dog.component.html',
  styleUrls: ['./dog.component.css'],
})
export class DogComponent {

  showDog: boolean = true;
  buttonPropText: String = "katt"

  toggleDogHandler() {
    this.showDog = !this.showDog;
    this.buttonPropText = this.showDog ? "katt" : "hund"
  }

}

<div class="center">
    <p>{{ dogState }}</p>
    <button (click)="toggleDogHandler()" class="btn" type="button">Toggle dog</button>
    <div>
        <img *ngIf="dogState"
            src="./assets/images/dog1.jpeg"
            alt="dog"
            class="img-responsive"
            style="max-height: 200px;">
        <img *ngIf="!dogState"
            src="./assets/images/dog2.jpeg"
            alt="dog"
            class="img-responsive"
            style="max-height: 200px;">
    </div>

</div>
